#!/bin/sh
# primary address: mainz2
/sbin/ip addr del dev $INTERFACE 10.207.1.37/16 broadcast 10.207.255.255
/sbin/ip -6 addr del dev $INTERFACE fec0::a:cf:1:25/96

# shutdown interface
/sbin/ip link set dev $INTERFACE down
