#!/bin/sh
/sbin/ifconfig ${INTERFACE} hw ether 02:00:0a:cf:25:07
/sbin/ip link set dev ${INTERFACE} up

# Insert routes for icvpn transfer-net
/sbin/ip -4 route add 10.207.0.0/16 proto static dev ${INTERFACE} table icvpn
/sbin/ip -6 route add fec0::/96 proto static dev ${INTERFACE} table icvpn

# primary address: mainz2
/sbin/ip addr add dev ${INTERFACE} 10.207.37.7/16 broadcast 10.207.255.255 scope link
/sbin/ip -6 addr add dev ${INTERFACE} fec0::a:cf:25:7/96 preferred_lft 0
