protocol bgp Augsburg1 from ebgp_ic {
    neighbor fec0::a:cf:0:a as 65050;
};

protocol bgp Bayreuth from ebgp_ic {
    neighbor fec0::a:cf:0:19 as 65025;
};

protocol bgp Berlin1 from ebgp_ic {
    neighbor fec0::a:cf:0:5 as 44194;
};

protocol bgp Bielefeld1 from ebgp_ic {
    neighbor fec0::a:cf:0:59 as 65529;
};

protocol bgp Bielefeld2 from ebgp_ic {
    neighbor fec0::a:cf:0:60 as 65529;
};

protocol bgp braunschweig1 from ebgp_ic {
    neighbor fec0::a:cf:0:28 as 65380;
};

protocol bgp braunschweig2 from ebgp_ic {
    neighbor fec0::a:cf:0:29 as 65380;
};

protocol bgp Bremen2 from ebgp_ic {
    neighbor fec0::a:cf:0:c4 as 65196;
};

protocol bgp Darmstadt1 from ebgp_ic {
    neighbor fec0::a:cf:0:218 as 65038;
};

protocol bgp Darmstadt2 from ebgp_ic {
    neighbor fec0::a:cf:0:219 as 65038;
};

protocol bgp dreilaendereck from ebgp_ic {
    neighbor fec0::a:cf:0:be as 65043;
};

protocol bgp dresden1 from ebgp_ic {
    neighbor fec0::a:cf:dd:1 as 65051;
};

protocol bgp dresden2 from ebgp_ic {
    neighbor fec0::a:cf:dd:2 as 65051;
};

protocol bgp flensborg1 from ebgp_ic {
    neighbor fec0::a:cf:0:10 as 65056;
};

protocol bgp flensborg2 from ebgp_ic {
    neighbor fec0::a:cf:0:11 as 65056;
};

protocol bgp Freiburg1 from ebgp_ic {
    neighbor fec0::a:cf:0:21 as 65060;
};

protocol bgp Gronau1 from ebgp_ic {
    neighbor fec0::a:cf:0:50 as 65526;
};

protocol bgp Gronau2 from ebgp_ic {
    neighbor fec0::a:cf:0:51 as 65526;
};

protocol bgp guetersloh1 from ebgp_ic {
    neighbor fec0::a:cf:0:84 as 65533;
};

protocol bgp guetersloh2 from ebgp_ic {
    neighbor fec0::a:cf:0:85 as 65533;
};

protocol bgp guetersloh4 from ebgp_ic {
    neighbor fec0::a:cf:0:86 as 65533;
};

protocol bgp hamburg01 from ebgp_ic {
    neighbor fec0::a:cf:0:3e as 65112;
};

protocol bgp hamburg05 from ebgp_ic {
    neighbor fec0::a:cf:0:41 as 65112;
};

protocol bgp Kiel0 from ebgp_ic {
    neighbor fec0::a:cf:0:34 as 65525;
};

protocol bgp Kiel3 from ebgp_ic {
    neighbor fec0::a:cf:0:3b as 65525;
};

protocol bgp Ljubljana1 from ebgp_ic {
    neighbor fec0::a:cf:3:23 as 65023;
};

protocol bgp Ljubljana2 from ebgp_ic {
    neighbor fec0::a:cf:3:30 as 64768;
};

protocol bgp Luebeck1 from ebgp_ic {
    neighbor fec0::a:cf:0:82 as 65052;
};

protocol bgp Luebeck2 from ebgp_ic {
    neighbor fec0::a:cf:0:83 as 65052;
};

protocol bgp magdeburg1 from ebgp_ic {
    neighbor fec0::a:cf:39:1 as 65039;
};

protocol bgp magdeburg2 from ebgp_ic {
    neighbor fec0::a:cf:39:2 as 65039;
};

protocol bgp monitoringmoehne from ebgp_ic {
    neighbor fec0::a:cf:0:120 as 65057;
};

protocol bgp ostholstein from ebgp_ic {
    neighbor fec0::a:cf:0:87 as 65152;
};

protocol bgp RheinNeckar from ebgp_ic {
    neighbor fec0::a:cf:0:142 as 76118;
};

protocol bgp rheinland0 from ebgp_ic {
    neighbor fec0::a:cf:0:4c as 65078;
};

protocol bgp rheinland1 from ebgp_ic {
    neighbor fec0::a:cf:0:4d as 65078;
};

protocol bgp rheinland2 from ebgp_ic {
    neighbor fec0::a:cf:0:4e as 65078;
};

protocol bgp ruhrgebiet1 from ebgp_ic {
    neighbor fec0::a:cf:0:9 as 65079;
};

protocol bgp Weimar1 from ebgp_ic {
    neighbor fec0::a:cf:0:3 as 65042;
};

protocol bgp Weimar2 from ebgp_ic {
    neighbor fec0::a:cf:0:4 as 65042;
};

protocol bgp Wermelskirchen1 from ebgp_ic {
    neighbor fec0::a:cf:0:7 as 65530;
};

protocol bgp Wermelskirchen2 from ebgp_ic {
    neighbor fec0::a:cf:0:8 as 65530;
};

protocol bgp wuppertal1 from ebgp_ic {
    neighbor fec0::a:cf:0:71 as 65523;
};
