#!/bin/sh

# http://manpages.ubuntu.com/manpages/maverick/en/man8/openvpn.8.html#contenttoc5

ip route add default via $route_vpn_gateway dev $dev table mz

ip route add default via $route_vpn_gateway dev $dev table wi

exit 0
