#!/bin/sh

# http://manpages.ubuntu.com/manpages/maverick/en/man8/openvpn.8.html#contenttoc5

set -x

ENVFILE="/tmp/ovpn-env-up"
echo "$@"  > "$ENVFILE"
env >> "$ENVFILE"

# TODO determine automatically
LOCAL_IP=`/sbin/ip -4 -o addr show dev eth0 | awk '{split($4,a,"/");print a[1]}'`
FFMZ_DEV="mzBR"
FFWI_DEV="wiBR"

manage_vpn_peer_routes() {
        ACTION="$1"
        ip route $ACTION "$route_vpn_gateway" dev "$dev" src "$ifconfig_local" table ffinetexit
}

manage_vpn_default_routes() {
        ACTION="$1"
        ip route $ACTION 0.0.0.0/1 via "$route_vpn_gateway" src "$ifconfig_local" table ffinetexit
        ip route $ACTION 128.0.0.0/1 via "$route_vpn_gateway" src "$ifconfig_local" table ffinetexit
}

if [ "$script_type" = "up" ]; then
        manage_vpn_peer_routes add
        manage_vpn_default_routes replace
elif [ "$script_type" = "down" ]; then
        manage_vpn_peer_routes del
fi

exit 0
