#!/bin/sh
/sbin/ip link set dev $INTERFACE up
/sbin/ip addr add dev $INTERFACE 10.207.0.37/16 broadcast 10.207.255.255
/scope link
/sbin/ip -6 addr add dev $INTERFACE fec0::a:cf:0:25/96 preferred_lft 0

# ip rules
/sbin/ip rule add lookup icvpn priority 10042
/sbin/ip -6 rule add lookup icvpn priority 10042