protocol bgp Augsburg1 from ebgp_ic {
    neighbor 10.207.0.17 as 65050;
};

protocol bgp Augsburg2 from ebgp_ic {
    neighbor 10.207.0.68 as 65050;
};

protocol bgp BadZwischenahn1 from ebgp_ic {
    neighbor 10.207.0.26 as 65025;
};

protocol bgp basel1 from ebgp_ic {
    neighbor 10.207.5.1 as 65090;
};

#protocol bgp Bayreuth1 from ebgp_ic {
#    neighbor 10.207.0.28 as 65025;
#};

protocol bgp Berlin1 from ebgp_ic {
    neighbor 10.207.0.5 as 44194;
};

protocol bgp Bielefeld1 from ebgp_ic {
    neighbor 10.207.0.59 as 65529;
};

protocol bgp Bielefeld2 from ebgp_ic {
    neighbor 10.207.0.67 as 65529;
};

protocol bgp braunschweig1 from ebgp_ic {
    neighbor 10.207.0.40 as 65380;
};

protocol bgp braunschweig2 from ebgp_ic {
    neighbor 10.207.0.41 as 65380;
};

protocol bgp Bremen2 from ebgp_ic {
    neighbor 10.207.0.196 as 65196;
};

protocol bgp Chemnitz1 from ebgp_ic {
    neighbor 10.207.0.36 as 65053;
};

protocol bgp darmstadt1 from ebgp_ic {
    neighbor 10.207.0.218 as 65038;
};

protocol bgp darmstadt2 from ebgp_ic {
    neighbor 10.207.0.219 as 65038;
};

protocol bgp dreilaendereck1 from ebgp_ic {
    neighbor 10.207.0.75 as 65043;
};

protocol bgp Dresden1 from ebgp_ic {
    neighbor 10.207.0.19 as 65051;
};

protocol bgp Dresden2 from ebgp_ic {
    neighbor 10.207.0.20 as 65051;
};

protocol bgp flensburg1 from ebgp_ic {
    neighbor 10.207.0.129 as 65056;
};

protocol bgp flensburg2 from ebgp_ic {
    neighbor 10.207.0.128 as 65056;
};

protocol bgp Franken1 from ebgp_ic {
    neighbor 10.207.0.23 as 65024;
};

protocol bgp Franken2 from ebgp_ic {
    neighbor 10.207.0.24 as 65024;
};

protocol bgp Franken3 from ebgp_ic {
    neighbor 10.207.0.31 as 65024;
};

protocol bgp Frankfurt1 from ebgp_ic {
    neighbor 10.207.0.35 as 65026;
};

protocol bgp Freiburg1 from ebgp_ic {
    neighbor 10.207.0.21 as 65060;
};

protocol bgp graz1 from ebgp_ic {
    neighbor 10.207.1.2 as 65048;
};

protocol bgp graz2 from ebgp_ic {
    neighbor 10.207.1.3 as 65048;
};

protocol bgp Gronau1 from ebgp_ic {
    neighbor 10.207.0.55 as 65526;
};

protocol bgp Gronau2 from ebgp_ic {
    neighbor 10.207.0.60 as 65526;
};

#protocol bgp Grossdraxdorf from ebgp_ic {
#    neighbor 10.207.0.25 as 65025;
#};

protocol bgp guetersloh1 from ebgp_ic {
    neighbor 10.207.0.132 as 65533;
};

protocol bgp guetersloh2 from ebgp_ic {
    neighbor 10.207.0.133 as 65533;
};

protocol bgp guetersloh3 from ebgp_ic {
    neighbor 10.207.0.134 as 65533;
};

protocol bgp Halle1 from ebgp_ic {
    neighbor 10.207.0.13 as 65046;
};

protocol bgp Halle2 from ebgp_ic {
    neighbor 10.207.0.14 as 65046;
};

protocol bgp hamburg01 from ebgp_ic {
    neighbor 10.207.0.62 as 65112;
};

protocol bgp hamburg05 from ebgp_ic {
    neighbor 10.207.0.65 as 65112;
};

protocol bgp Hannover1 from ebgp_ic {
    neighbor 10.207.0.22 as 65511;
};

protocol bgp Jena1 from ebgp_ic {
    neighbor 10.207.0.33 as 65055;
};

protocol bgp Jena2 from ebgp_ic {
    neighbor 10.207.0.66 as 65055;
};

protocol bgp kbu from ebgp_ic {
    neighbor 10.207.0.57 as 65528;
};

protocol bgp Koblenz from ebgp_ic {
    neighbor 10.207.0.32 as 65032;
};

protocol bgp Leipzig1 from ebgp_ic {
    neighbor 10.207.0.1 as 65041;
};

protocol bgp Leipzig2 from ebgp_ic {
    neighbor 10.207.0.2 as 65041;
};

protocol bgp Ljubljana1 from ebgp_ic {
    neighbor 10.207.3.23 as 65023;
};

protocol bgp Ljubljana2 from ebgp_ic {
    neighbor 10.207.3.30 as 65023;
};

protocol bgp Luebeck1 from ebgp_ic {
    neighbor 10.207.0.130 as 65052;
};

protocol bgp Luebeck2 from ebgp_ic {
    neighbor 10.207.0.131 as 65052;
};

protocol bgp luenen from ebgp_ic {
    neighbor 10.207.0.34 as 65034;
};

protocol bgp magdeburg1 from ebgp_ic {
    neighbor 10.207.39.1 as 65039;
};

protocol bgp magdeburg2 from ebgp_ic {
    neighbor 10.207.39.2 as 65039;
};

protocol bgp moehne1 from ebgp_ic {
    neighbor 10.207.0.120 as 65057;
};

protocol bgp muenchen1 from ebgp_ic {
    neighbor 10.207.0.80 as 65080;
};

protocol bgp Oldenburg1 from ebgp_ic {
    neighbor 10.207.0.27 as 65513;
    debug { states,interfaces,events };
};

protocol bgp Oldenburg2 from ebgp_ic {
    neighbor 10.207.0.38 as 65513;
};

protocol bgp ostholstein1 from ebgp_ic {
    neighbor 10.207.0.135 as 65152;
};

protocol bgp rheinland0 from ebgp_ic {
    neighbor 10.207.0.76 as 65078;
};

protocol bgp rheinland1 from ebgp_ic {
    neighbor 10.207.0.77 as 65078;
};

protocol bgp rheinland2 from ebgp_ic {
    neighbor 10.207.0.78 as 65078;
};

protocol bgp RheinNeckar from ebgp_ic {
    neighbor 10.207.0.142 as 76118;
};

protocol bgp ruhrgebiet1 from ebgp_ic {
    neighbor 10.207.0.79 as 65079;
};

#protocol bgp stuttgart from ebgp_ic {
#    neighbor 10.207.0.11 as 65045;
#};

protocol bgp Treuenbrietzen from ebgp_ic {
    neighbor 10.207.0.18 as 65045;
};

protocol bgp Weimar1 from ebgp_ic {
    neighbor 10.207.0.3 as 65042;
};

protocol bgp Weimar2 from ebgp_ic {
    neighbor 10.207.0.4 as 65042;
};

protocol bgp Wermelskirchen1 from ebgp_ic {
    neighbor 10.207.0.7 as 65530;
};

protocol bgp Wermelskirchen2 from ebgp_ic {
    neighbor 10.207.0.8 as 65530;
};

protocol bgp weststeiermark1 from ebgp_ic {
    neighbor 10.207.0.51 as 65054;
};

protocol bgp wuppertal1 from ebgp_ic {
    neighbor 10.207.0.73 as 65523;
};
