#!/bin/sh
/sbin/ifconfig ${INTERFACE} hw ether 02:00:0a:cf:01:38
/sbin/ip link set dev $INTERFACE up
/sbin/ip addr add dev $INTERFACE 10.207.1.56/16 broadcast 10.207.255.255 scope link
/sbin/ip -6 addr add dev $INTERFACE fec0::a:cf:1:38/96 preferred_lft 0

# ip rules
/sbin/ip rule add lookup icvpn priority 10042
/sbin/ip -6 rule add lookup icvpn priority 10042
